site_name: WI 2018 wiki
nav:
  - Wstęp: index.md
  - Plan: plan.md
  - Wykłady: wyklady.md
  - Laboratoria: laboratoria.md
  - Materiały: materialy.md
  - Dokumentacja: dokumentacja.md
theme: readthedocs
markdown_extensions:
  - admonition
google_analytics: ['UA-179605180-1', 'wi.ptl.cloud']
