site_name: WI 2018 wiki
nav:
  - Wstęp: index.md
  - Plan: plan.md
  - Prowadzacy: prowadzacy.md
  - Materiały: materialy.mdplugins:
8
  - 
  - Zajęcia: zajecia.md
theme: readthedocs
markdown_extensions:
  - admonition
